turnitin/moodle-mod_turnitintooltwo

backup/moodle2/restore_turnitintooltwo_stepslib.php

Added parameter requirement to search for course_type = 'TT' to fix bug where restore was grabbing the wrong classes.

Added TT to query in stepslib

---

classes/digitalreceipt/receipt_message.php

Modified object variable in `receipt_message->send_message` to replace the site administrator address with the site default noreply address.

Send submission receipts from noreply instead of admin

---

classes/digitalreceipt/instructor_message.php

Fixed a bug where messages for 'Turnitin Assignment Instructor Digital Receipt notifications' was sent as 'Turnitin Assignment Digital Receipt notifications'. This cause disabling the setting of 'Turnitin Assignment Instructor Digital Receipt notifications' have no effect.
It is related to issue #148

Fixed teachers receiving submission notifications.

---

classes/digitalreceipt/instructor_message.php

Reverts turnitin/moodle-mod_turnitintooltwo#156
subsequent testing shows that this disables all receipt notifications of this nature.

Revert "Fixed teachers receiving submission notifications."

---

ajax.php

- I realised we only need one language string for displaying the status message so condensed the variables to just $statusText.
- Also fixed the can migrate variable as it differs depending on trial or actual migration, by placing it within the if statement.
- Also contains a fix for the file close variable that I noticed.

Fixes for language string output in CSV

---

ajax.php

Fixes issue where null values in Erater could cause the script to halt.
Also added the same check for other fields just in case.

Fixes issue where null values in Erater (or other fields) could cause the script to halt.

---

ajax.php
logs/migrationtool/debug/.gitignore

Adds a debugging log that is created during a run of the migration tool. This helps us determine which part of the tool is being slow. I didn't place the strings into the language string file as this is just for us and we may decide to remove it before releasing the tool.

Add debugging to migration tool

---

ajax.php
db/install.xml
db/upgrade.php
lib.php
version.php

This changes the functionality of the migration tool to prevent the tool from exceeding the database transaction lock timeout limit when migrating a course. The scenario is caused by Moodle's gradebook updates being slow, which adds up quickly for thousands of submissions. 
The change moves this functionality from the migration tool to the background cron without affecting migrations. It updates the gradebook in order of latest modified submissions.
Also some slight modifications to the debug output layout.

INT-6237 - Move gradebook updates to the cron

---

turnitintooltwo_view.class.php

Noticed that `$i` was set and incremented but never called. Removing.

remove dud variable from get_submissions_inbox

---

jquery/turnitintooltwo.js

In Moodle 3.1 the submission processing text and icon are not being displayed as the form validation stopped working in 3.1. this pull request fixes that.

INT-7637 - Fix submission processing message in Moodle 3.1

---

turnitintooltwo_assignment.class.php

If a student has been deleted in Turnitin and has a submission in Moodle then the assignment inbox will fail to load. This fixes the issue by detecting the deleted user and not refreshing the submission.

INT-7659 Fix for deleted Turnitin student not allowing inbox to load

---

classes/helpdeskwizard/helpdeskwizard.php
classes/v1migration/v1migration.php
extras.php
jquery/turnitin_helpdesk.js
lang/en/turnitintooltwo.php
lib.php
tests/unit/classes/v1migration/v1migration_test.php
tests/unit/lib.php
tests/unit/turnitintooltwo_assignment_test.php
turnitintooltwo_assignment.class.php
turnitintooltwo_submission.class.php
turnitintooltwo_view.class.php
view.php

Add support for two V2 courses.
This solves the issue where we have pre-existing V2 assignments on a course with a different Turnitin class to the V1 assignment.
Also passed in a course type parameter to help differentiate between the two courses, and a legacy field to indicate which course should be looked up post-migration.

Add support for two V2 courses

---

tests/unit/turnitintooltwo_assignment_test.php
turnitintooltwo_assignment.class.php

This fixes checkbox settings when editing an assignment that were always being set to 0, irrespective of what they were set to.

Fix checkbox settings that were always being set to 0

---

classes/v1migration/v1migration.php

Added extra uniqueness to the hashing.
Unit test failures detected, but are unrelated to this change:
```
1) mod_lib_testcase::test_turnitintooltwo_cron_migrate_gradebook_1000
Failed asserting that 400 matches expected 0.
```

modify hash generation to use uniqid with extra unique-ness

---

ajax.php
jquery/turnitintooltwo_migration_tool.js

Using .length on a property that doesn't exist will throw an error. This PR changed to Object.hasOwnProperty().

INT-9107: Fix debug length check

---

turnitintooltwo_assignment.class.php

This is a fix for issue #371
A variable $context is being used further down in the method, but it has not been set at that point.

$context was not set when used in get_suspended_userids()

---

turnitintooltwo_assignment.class.php

this seems to fix the failures for us - basic structure copied from tests/unit/generator/lib.php make_test_tii_assignment() - not sure if you'll want to combine those into a more central function instead of merging this in.

Fix #366 Unit test failures in Moodle 3.3

---

classes/digitalreceipt/instructor_message.php
classes/digitalreceipt/receipt_message.php
classes/nonsubmitters/nonsubmitters_message.php
mod_form.php
tests/unit/classes/nonsubmitters/nonsubmitters_message_test.php
turnitintooltwo_view.class.php
view.php

Fixes send_message warnings for 3.2+/error in 3.5.
Fixes an issue where an undefined parameter would appear in the assignment setup page.
Fixes an issue where an undefined parameter would appear for a sudent who has not accepted the EULA.
Note: These would only appear with debugging on.

Fix send message and some minor fixes.

---

lib.php
tests/unit/lib_test.php
turnitintooltwo_assignment.class.php
view.php

This pull request fixes three areas that were missed during the implementation of Moodle 3.3+ course overview support in the previous release:
- The date now updates when the due date is updated.
- The dates now update on a course reset if the reset is set to use new assignment dates.
- Previously created assignments will now update to use the new course overview functionality automatically when an instructor opens an assignment. (this allows for backwards compatibility with assignments created on older versions)
I've also removed some now redundant pre 2.6 code as the plugin requires a higher version of Moodle than that anyway.

Improvements to course overview timeline functionality.

---

lib.php

Fix for an issue where non-ASCII characters in file name cause issues in Windows.

Fix for an issue where non-ASCII characters in file name cause issues in Windows.

---

db/install.php

Copy across student privacy settings from V1 (if it exists) when the plugin is installed.

Copy across student privacy settings from V1 (if it exists) when the plugin is installed.

---

lib.php
mod_form.php

Turnitin assignment v2 isn't supposed to respect the parts deletion flag any more?  This patch is intended to ignore the parts deletion flag in a couple of places where it is still checked.
(I can't test it out though, so I don't really know if it's right.)

Ignore parts deletion flag (untested)

---

lib.php

Plugins in Moodle can declare they wish to control the visibility of items in the gradebook.
This patch puts the Turnitin tool plugin in control of the visibility of it's own gradebook items.
Users should no longer be able to edit the visibility of it's grade items via the gradebook.
Grades will be set to become avaliable from the highest post date, unless the Turnitin activity is hidden in which case the grade items will be hidden.

Turnitin should control visibility of gradebook items

---

lib.php
tests/unit/lib_test.php

Update event is called but it's possible that the no event may exist as it could have been deleted during e.g. course reset. This PR creates an event if necessary.

Create event if it does not exist when update has been called.

---

turnitintooltwo_assignment.class.php

This should resolve issue #605 
when turnitintooltwo can't find the record on mdl_turnitintooltwo because it has been deleted (maybe due to race condition or some other errors) , it should return true just like Moodle does here:
https://github.com/moodle/moodle/blob/master/course/lib.php#L1141-L1142

Issue #605: cron fail on adhoc task course_delete_modules

---

classes/digitalreceipt/receipt_message.php

We've detected that the messages send by Turnitin to submitters don't apply the Moodle filters (we use filter_multilang2, but it may happen also with order filters), this change fixes that.

Add filter support to submitter message

---

classes/digitalreceipt/instructor_message.php

We've detected that the messages send by Turnitin to instructors don't apply the Moodle filters (we use filter_multilang2, but it may happen also with order filters), this change fixes that.

Add filter support to instructor message

---

tests/unit/classes/digitalreceipt/instructor_message_test.php
tests/unit/classes/digitalreceipt/receipt_message_test.php
tests/unit/classes/v1migration/v1migration_test.php
tests/unit/classes/view/members_test.php
tests/unit/classes/view/turnitintooltwo_view_test.php
tests/unit/turnitintooltwo_assignment_test.php
tests/unit/turnitintooltwo_comms_test.php
version.php

Fixing unit tests that were broken as a result of a previously merged pul request. The tests also needed the string formatter. I have also changed the use of assertContains to the recommended alternative as that one was deprecated a long time ago.

Fixing broken unit tests

---

sdk/soap.class.php

`ReturnTypeWillChange` hides warning in PHP 8.1 and is ignored as a comment in earlier versions.

INT-18633 supress warning with attribute flag

---

tests/unit/classes/view/turnitintooltwo_view_test.php

Since MDL-78806, the site name of the site is now being included in the page title of Moodle pages in order to improve the accessibility of page titles.
For more information, check out:
https://www.w3.org/WAI/WCAG21/Techniques/general/G88

Less strict checking of the expected title string in the page title

---

lib.php
turnitintooltwo_assignment.class.php

When debug messages are set to DEVELOPER the following issues will throw error messages:
- Applying current() to an object directly is now deprecated. Forcing type array before will solve this.
- Using null as a parameter for is_nan() is now deprecated. Checking if parameter is set before will solve this.

Fix deprecated function usages

---

lib.php

Applying current to an object is now deprecated.
Forcing type array before will solve this.
credit @opitz
rebased on develop from ucl-isd#9

forcing array type before using current()

---

tests/unit/classes/view/turnitintooltwo_view_test.php

In #736 we added a new column, therefore the hidden table used for sorting should span 17 columns instead of 16
This resolves #750

Fix unit test

---

turnitintooltwo_view.class.php

When a part of an assignment has max grade of zero and we display the grade as a percentage, we get a division by zero error that results in an error 500. We need to check that maxmarks is greater than zero before doing the division. Otherwise, just show the submission grade instead of a percentage.

Fix division by zero error

---

sdk/soap.class.php

We are currently suppressing the missing return type warning for the function __doRequest. For good practice we should declare the return type explicitly instead.

Add return type for __doRequest

---

view.php

Right now we don't respect the 'Allow Submission of Any File Type' option. We are currently allowing submission of any file type regardless of whether this option is set or not.
I have added a list of file types to accept based on this guide: https://guides.turnitin.com/hc/en-us/articles/23929463501965-File-requirements 
It is important that the list of accepted file extensions is accurate, so please could any reviewers check it and let me know if there are any that are wrong or any more I need to add.

Respect allowed file types option

---

extras.php
settings_extras.php

As of Moodle 3.6, coursecatlib is deprecated. This PR replaces our usage of coursecat::make_categories_list with core_course_category::make_categories_list

Replace deprecated coursecatlib.php

---

turnitintooltwo_assignment.class.php

We are currently checking the value of a variable before it is assigned. This means that suspended users will not be excluded properly from course enrolment.

Fix undefined variable $user

---

settings_extras.php

We are getting an error that prevents data dumps from being displayed and saved because newer PHP versions don't allow calling substr on a null string. Therefore we need a null check when displaying nullable values.

Add null check in data dump

---

turnitintooltwo_assignment.class.php

Beforehand, we didn't copy the "intro" text into our db. This meant that if we wanted to copy a moodle V2 assignment to an LTI 1.3 assignment, the intro could never get copied because there was nothing in the db in the first place.
Part of https://turnitin.atlassian.net/browse/INT-20016

Ensuring intro is saved in our db to facilitate assignment copy

---

turnitintooltwo_view.class.php

Our logic that checks for ability to notify nonsubmitters appears to have broken flow control, in versions past 4.0 it never returns false.
At this point we can also drop support for Moodle versions less than 4.0 so can cleanup some unused code there.

Fix logic for enable notify nonsubmitters

---

view.php

This library was deprecated in Moodle 2.7 and was removed in Moodle 5.0, therefore we need to remove it

Removing uploadlib

---

lib.php
turnitintooltwo_assignment.class.php

We are currently creating duplicate events in the Moodle calendar when we change the name of a TT assignment part. This is because in our logic to update an existing calendar event we find the event using a sql query with the event name. Since the name has just been changed, we look for the event using the new name and fail to find it, so instead of updating the old record a new one is created. To fix this I delete the event before updating the name. After that the name is updated, the new event is created.
You may very well ask why we don't just store the ID of the event as a foreign key in the TT database table. To that I say good question. I agree this would be a better solution, but it would require adding database fields and would not be backward compatible when migrating plugin …

Delete old calendar events before creating new ones

---

turnitintooltwo_assignment.class.php

passing NULL triggers are PHP deprecation warning when preg_replace() is called from within this core function.
fixes #793

prevent passing NULL to strip_pluginfile_content().

---

turnitintooltwo_assignment.class.php

It's possible for the session variable tiisubmissions to be null if the call to TFS fails. Later code relies on this, so we should set a default value of an empty array.

If TFS request fails, setting submissions to empty list

---

turnitintooltwo_assignment.class.php

Sometimes get_coursemodule_from_instance can fail, which results in the cron breaking.
We need better error checking around this.
We probably also need to check whether the activity/course has been deleted and delete the activity if it's no longer valid

Checking for failed get_coursemodule_from_instance

---

turnitintooltwo_assignment.class.php

When updating the rubric for an assignment, if the transmatch setting is not set we get an exception. This adds a default value.

Adding null check for transmatch
