turnitin/moodle-mod_turnitintooltwo

- jquery/turnitintooltwo.js
- turnitintooltwo_view.class.php
- view.php
Remember selected part on submission deletion.
> Remember selected part on submission deletion.

- turnitintooltwo_user.class.php
Delete TII user record on unlink user if Moodle user has already been deleted.
> Delete TII user record on unlink user if Moodle user has already been deleted.

- jquery/jquery.dataTables.css
- jquery/jquery.dataTables.js
> Update data tables.

- jquery/turnitintooltwo.js
Change EULA link modal to open differently due to theme conflicts.
> Change EULA link modal to open differently due to theme conflicts.

- ajax.php
- jquery/turnitintooltwo_settings.js
Progress bar bug fix + change to V1 title.
> Progress bar bug fix + change to V1 title.

- turnitintooltwo_assignment.class.php
Fix for default grade options.
> Fix for default grade options.

- ajax.php
- turnitintooltwo_submission.class.php
> Migrate gradebook grades

- CHANGELOG.md
> Release v2015040111

- lang/en/turnitintooltwo.php
Output success message in cron.
> Output success message in cron.

- turnitintooltwo_user.class.php
Set a default for first name/last name if the field is empty.
> Set a default for first name/last name if the field is empty.

- turnitintooltwo_user.class.php
> Add a trim to trim spaces.

- view.php
Remove unnecessary view line from activity log.
> Remove unnecessary view line from activity log.

- settings_extras.php
> Logic fix for API URL.

- lang/en/turnitintooltwo.php
Language string for PP cron events queue.
> Language string for PP cron events queue.

- db/install.xml
- db/upgrade.php
- version.php
Anonymous grades in gradebook flag once post date passes.
> Anonymous grades to gradebook flag 5092

- lib.php
- turnitintooltwo_assignment.class.php
Send anonymous marking grades to the gradebook.
> Anonymous grades to gradebook 4966

- TROUBLESHOOTING.md
- lang/en/turnitintooltwo.php
- settings.php
List MB String PHP extension as plugin requirement.
> List MB String PHP extension as plugin requirement.

- classes/digitalreceipt/receipt_message.php
- lang/en/turnitintooltwo.php
- settings.php
- turnitintooltwo_submission.class.php
Resolving conflicts on https://github.com/turnitin/moodle-mod_turnitintooltwo/pull/87
> Resolving lang conflicts from #87

- turnitintooltwo_user.class.php
Remove user updated log entry.
> Remove user updated log entry.

- lib.php
Fix bug where the grades aren't updated when parts have been deleted.
> Fix bug where the grades aren't updated when parts have been deleted.

- lang/en/turnitintooltwo.php
Language string for PP Pending issue for temp file creation error.
> Language string for PP Pending issue for temp file creation error.

- settings_extras.php
> Fix for repository setting

- settings_extras.php
Fix for when no setting differences are present.
> Fix for when no setting differences are present.

- lib.php
Postgre SQL fix for anonymous marking gradebook update.
> Postgre SQL fix for anonymous marking gradebook update.

- ajax.php
Update to fix problem when CSV is opened for the first time via trial migration
> Update to fix problem when CSV is opened for the first time via trial migration

- lang/en/turnitintooltwo.php
Changed support links to open in new tab/window.
> Changed support links to open in new tab/window.

- sdk/oauthsimple.class.php
Recreated changes from pull request #86 in my own branch in order to merge into develop rather than master.
> Replicated changes from pull request 86 by joebaba.

- ajax.php
Add transactions to course migration structure
> Add transactions to course migration structure

- turnitintooltwo_submission.class.php
- view.php
Fix activity log submission entry.
> Fix activity log submission entry.

- lang/en/turnitintooltwo.php
- settings_extras.php
Explain the differences between the V1 and V2 institutional repository setting.
> Explain the differences between the V1 and V2 institutional repository setting.

- turnitintooltwo_submission.class.php
Enrol user when saving a submission if necessary.
> Enrol user when saving a submission if necessary.

- jquery/turnitintooltwo.js
> Comment was incorrect.

- ajax.php
- lang/en/turnitintooltwo.php
- settings.php
- turnitintooltwo_comms.class.php
- turnitintooltwo_user.class.php
API log changes to make them less confusing.
> API log changes to make them less confusing.

- CHANGELOG.md
- version.php
> Staged for release.

- settings_extras.php
> Fix for extra parameter.

- .gitignore
- logs/migrationtool/.gitignore
Readded empty log directories.
> Readded empty log directories.

- ajax.php
- classes/csvexport/export_courses.php
- settings_extras.php
Changed CSV export to generate as the tool is running.
> Changed CSV export to generate as the tool is running.

- db/install.xml
Fix for incorrect data type in turnitintooltwo_courses
> Fix for incorrect data type in turnitintooltwo_courses

- classes/digitalreceipt/instructor_message.php
- db/messages.php
Replicating the original PR and modifying a comment to be more descriptive.
> Fix int 5894 instructor receipts

- lib.php
Fix for issue where old assignment deletions would break schedule tasks if there is an entry in turnitintooltwo table but not course_modules
> Fix for issue where old assignment deletions would break schedule tasks

- ajax.php
- settings_extras.php
Handle empty object correctly on line 842. Everything else is just white space changes.
> INT-6202 - Handle empty object correctly

- ajax.php
Fixes issue where migration tool can fail if no V2 course is found.
> Fixes issue where migration tool can fail if no V2 course is found.

- ajax.php
Correct variable name for CSV file close.
> INT-6201- Correct variable name for CSV file close.

- turnitintooltwo_assignment.class.php
- turnitintooltwo_submission.class.php
- turnitintooltwo_user.class.php
- turnitintooltwo_view.class.php
Modify to display user's email instead of username
> Modify to display name using Moodle fullname function

- CHANGELOG.md
- version.php
Release notes and version number.
> Release notes and version number.

- ajax.php
Add course limitations - ensure it only counts students
> Add course limitations - ensure it only counts students

- backup/moodle2/restore_turnitintooltwo_activity_task.class.php
- turnitintooltwo_assignment.class.php
Fixes the issue where course restore would fail when encountering assignments created more than a year ago.
> Fix for course restore on assignments over 1 year old.

- ajax.php
> Change max students to 3000

- turnitintooltwo_assignment.class.php
Amended fix for issue where restoring a course with assignments over a year old would not work as intended.
> Amended fix for course restore on assignments over 1 year old. 

- turnitintooltwo_view.class.php
This pull request adds an anonymous marking check before the assignment inbox is loaded so that the overall grade is calculated if all parts are unanonymised.
> INT-6932 - Overall grade display when anonymous marking is enabled

- turnitintooltwo_assignment.class.php
This supercedes https://github.com/turnitin/moodle-mod_turnitintooltwo/pull/183 due a merge conflict with a function we've subsequently removed.
> Remove suspended users from all user functions (thanks to @junwan6)

- turnitintooltwo_assignment.class.php
- view.php
Also rename variable in assignment class. Thanks to @junwan6
> Remove suspended users from non submitters email

- view.php
This pull request fixes the issue where errors could occur on Windows servers if a submission is uploaded with characters that aren't permitted in Windows file system.
> INT-7672 - Fix issue with submission titles and special characters.

- backup/moodle2/restore_turnitintooltwo_stepslib.php
- db/install.xml
- db/upgrade.php
- turnitintooltwo_submission.class.php
- turnitintooltwo_view.class.php
- version.php
Add prevention for duplicate submission rows in database.
> Add prevention for duplicate submission rows in database.

- backup/moodle2/restore_turnitintooltwo_stepslib.php
Fix for course restore for our duplicate database rows fix.
> Fix for course restore for our duplicate database rows fix.

- backup/moodle2/restore_turnitintooltwo_stepslib.php
- lib.php
- sdk/soap.class.php
Fixes the restore bug we found as a result of our duplicate fix.
> Restore fix in V2.

- CHANGELOG.md
- version.php
> Release notes v2017012501

- tests/unit/turnitintooltwo_submission_test.php
- turnitintooltwo_submission.class.php
Adding some unit tests for the turnitintooltwo_submission class. This is only a start, we will add more tests for this class as time passes.
> Added some tests for the create submission workflow.

- CHANGELOG.md
- turnitintooltwo_submission.class.php
> Send revealing user when revealing anonymous submissions

- CHANGELOG.md
- turnitintooltwo_submission.class.php
Reverts turnitin/moodle-mod_turnitintooltwo#267
> Revert "Send revealing user when revealing anonymous submissions"

- turnitintooltwo_submission.class.php
Refactor of update gradebook for migration tool prototype.
> Refactor of update gradebook for migration tool prototype.

- turnitintooltwo_assignment.class.php
Enable anonymous marking on newly created parts if it is meant to be on.
> Enable anonymous marking on newly created parts if it is meant to be on.

- .gitignore
- sdk/oauthsimple.class.php
- turnitintooltwo_class.class.php
- add .vscode dir to gitignore in case future plugins create junk
- correct docComment errors to eliminate linter warnings
> Some elementary housekeeping

- db/install.xml
- db/upgrade.php
- version.php
> Legacy database field

- classes/v1migration/v1migration.php
Exclude PP from migrate_course function.
> Exclude PP from migrate_course function.

- classes/helpdeskwizard/helpdeskwizard.php
Populate support wizard dropdowns.
> Populate support wizard dropdowns.

- lib.php
- tests/unit/lib_test.php
Limit cron gradebook migrations to 1000.
> Limit cron gradebook migrations to 1000.

- turnitintooltwo_submission.class.php
Remove digital receipt from nothing submission.
> Remove digital receipt from nothing submission.

- classes/v1migration/v1migration.php
This PR:
* Truncates the title based on the length of the title combined with the prefix, if it's greater than 255.
> INT-8998: Truncate V1 title if needed

- classes/v1migration/v1migration.php
Change delay to 5 seconds and make migrations per sleep a variable based on this constant.
> Change delay to 5 seconds and make migrations per sleep a variable based on this constant.

- turnitintooltwo_assignment.class.php
Change to string file content and images from calendar events.
> Change to string file content and images from calendar events.

- ajax.php
- jquery/turnitintooltwo_migration_tool.js
- lang/en/turnitintooltwo.php
This PR:
* Catches exceptions thrown during the migration process in ajax.php and returns the data in the ajax call to be handled by the JS.
> feat: handle exceptions in migration

- ajax.php
- classes/v1migration/v1migration.php
- jquery/turnitintooltwo_migration_tool.js
This PR:
* Outputs a more "dev friendly" error in the console if the migration fails and developer mode is enabled for Moodle.
> Output in the JS console a stack trace if debugging enabled

- classes/v1migration/v1migration.php
- settings_extras.php
- tests/unit/classes/v1migration/v1migration_test.php
- tests/unit/generator/lib.php
- Change delete course method to use Moodle's function which takes care of everything.
- Fix broken tests and use generator for module creation.
- Slight reworking of user migration.
> Change course module deletion method

- classes/v1migration/v1migration.php
- tests/unit/classes/v1migration/v1migration_test.php
Only migrate the latest v1 submission. This means we have to check the hash before inserting into the submissions table and do an update instead.
> Account for multiple submissions in v1

- backup/moodle2/backup_turnitintooltwo_activity_task.class.php
- backup/moodle2/restore_turnitintooltwo_activity_task.class.php
Fix for for link mapping in backup and restore.
> Fix for for link mapping in backup and restore.

- backup/moodle2/backup_turnitintooltwo_stepslib.php
- institutioncheck and allownonor were missing
> Add missing backup params

- lang/en/turnitintooltwo.php
- lib.php
- turnitintooltwo_view.class.php
This pull request adds tooltips to icons within the inbox and changes the download submission button icon from a cloud to the proper download icon.
This pull request reproduces the work done in #223 by @rlorenzo as that could not be merged due to conflicts.
> Add tooltips to icons.

- ajax.php
- classes/v1migration/v1migration.php
- tests/unit/classes/v1migration/v1migration_test.php
- turnitintooltwo_assignment.class.php
Allow unenrolled users submissions to be migrated
> Fix hash for unenrolled users

- CHANGELOG.md
- version.php
> Release 2017070301

- db/upgrade.php
- version.php
> Version update.

- CHANGELOG.md
- db/upgrade.php
- version.php
> Migration tool release notes

- CHANGELOG.md
- db/upgrade.php
- turnitintooltwo_view.class.php
- version.php
> Migration tool release

- CHANGELOG.md
Fix broken image in release notes.
> Fix broken image in release notes.

- classes/search/activity.php
Very basic global search implementation
> Add core activity search

- lib.php
MS SQL fix for anonymous marking grades to gradebook.
> MS SQL fix for anonymous marking grades to gradebook.

- classes/v1migration/v1migration.php
> Add operation param to URL.

- lib.php
this seems to work for me but probably good for you guys to test as usual.
> Fix #387 unit test failures

- backup/moodle2/backup_turnitintooltwo_stepslib.php
- turnitintooltwo_assignment.class.php
Fixes for calendar/tests/container_test.php unit test based on DM's contribution
> Fixes for calendar/tests/container_test.php unit test based on DM's contribution

- tests/unit/generator/lib.php
- tests/unit/turnitintooltwo_comms_test.php
Remove unused function, change test domain.
> Remove unused function, change test domain.

- CHANGELOG.md
- db/upgrade.php
- version.php
> Release 2017103001

- classes/v1migration/v1migration.php
Fix to migration tool prompt for Moodle 3.4
> Fix to migration tool prompt for Moodle 3.4

- CHANGELOG.md
- version.php
> Release 2017112301

- CHANGELOG.md
- version.php
> Release 2018011601

- CHANGELOG.md
- lang/en/turnitintooltwo.php
- lib.php
- mod_form.php
- settings.php
- tests/unit/lib_test.php
- turnitintooltwo_assignment.class.php
- turnitintooltwo_submission.class.php
> Feature - Allow ability to force Institutional Repo

- turnitintooltwo_submission.class.php
Send correct anonymous reveal user
> Send correct anonymous reveal user.

- classes/digitalreceipt/instructor_message.php
- classes/digitalreceipt/receipt_message.php
- classes/nonsubmitters/nonsubmitters_message.php
- tests/unit/classes/view/turnitintooltwo_view_test.php
- turnitintooltwo_user.class.php
Fix broken unit tests for send_message and table structure.
> Fix broken unit tests for send_message and table structure.

- CHANGELOG.md
- version.php
> Release 2018052301

- mod_form.php
- turnitintooltwo_user.class.php
Fixing undefined indexes for instructor defaults and submitpapersto.
> Fixing undefined indexes for instructor defaults and submitpapersto.

- CHANGELOG.md
- version.php
Releasing Moodle Direct V2 2018082801
> Releasing Moodle Direct V2 2018082801

- settings.php
- turnitintooltwo_view.class.php
Removed lines of code that were redundant, resulting in default grade setting being removed from Admin Settings. 
Checked if this effected assignment creation- it did not.
> Removed default grade setting from Admin Settings

- lib.php
- mod_form.php
Add htmlentities to title field.
> Add htmlentities to title field.

- turnitintooltwo_view.class.php
Hide resubmission message from student if the instructor has hidden the OR.
> Hide resubmission message from student if the instructor has hidden the OR.

- CHANGELOG.md
- version.php
> Release v2018121801

- classes/v1migration/v1migration.php
Ensure the grade category is migrated with the assignment.
> Ensure the grade category is migrated with the assignment.

- CHANGELOG.md
- classes/v1migration/v1migration.php
- version.php
> Release v2018122101

- classes/v1migration/v1migration.php
- version.php
Fix grade category check where none exists.
> Fix grade category check where none exists.

- classes/v1migration/v1migration.php
Add grade to pass parameter to migration.
> Add grade to pass parameter to migration.

- view.php
Do not strip tags from text submission.
> Do not strip tags from text submission.

- CHANGELOG.md
- version.php
> Release branch 2019012401

- classes/v1migration/v1migration.php
Added to array, to ensure that deleted parts are no longer migrated.
> fix-deleted parts no longer migrated

- classes/privacy/provider.php
- lang/en/turnitintooltwo.php
- tests/unit/classes/privacy/provider_test.php
Adding privacy provider line about the content we send.
> Adding privacy provider line about the content we send.

- CHANGELOG.md
- version.php
> Releasing v2019050101

- settings_extras.php
Change made, removed nab var to allow correct styling.
> removed navbar to allow correct styling in 3.7

- CHANGELOG.md
- version.php
> Release v2019070201

- lib.php
Updating undefined value assignmentpart->max
> Updating undefined value assignmentpart->max

- turnitintooltwo_view.class.php
* Making sure empty headers are <th> tags to fix broken JS.
See https://github.com/turnitin/moodle-mod_turnitintooltwo/issues/573 for more details on the error.
> Fixes Student view broken #573

- backup/moodle2/backup_turnitintooltwo_stepslib.php
> Sort activity parts when creating a backup

- mod_form.php
> Issue #572 - Removed CSS class causing misalignment of form element

- CHANGELOG.md
- version.php
Release notes and version number.
> Release v2022020301

- mod_form.php
> fixed optional parameter before required parameter issue with show_form()

- turnitintooltwo_assignment.class.php
Notice: Undefined variable: coursetype in /path/to/moodle/mod/turnitintooltwo/turnitintooltwo_assignment.class.php on line 380
Seems related to ab9b32c4db257f43c7e8dcdc1f4950f7af5a8884 and this bit having been skipped
> Fix undefined coursetype

- mod_form.php
Abort definition() if page output has begun.
This will fix #706.
> Fix failing Behat test

- turnitintooltwo_user.class.php
I found the fix from our old fork.
Please review and merge if it's ok.
> Fix issue #709

- sdk/api.class.php
- sdk/assignmentsoap.class.php
- sdk/classsoap.class.php
- sdk/log.class.php
- sdk/lti.class.php
- sdk/membershipsoap.class.php
- sdk/response.class.php
- sdk/soap.class.php
- sdk/submissionsoap.class.php
- sdk/tiiassignment.class.php
- sdk/tiiclass.class.php
- sdk/tiilti.class.php
- sdk/tiisubmission.class.php
- sdk/tiiuser.class.php
- sdk/usersoap.class.php
> fix missing slashes in sdk inclusion paths

- package-lock.json
- package.json
Resolves a security vulnerability
> Upgrade postcss transitive dependency

- mod_form.php
The character limit for an assignment introduction (summary) in TFS is 1000 characters.
This PR adds missing form validation for this.
> Add character limit for summary

- db/upgrade.php
- version.php
Adding missing php code from #813
> XMLDB index update
